apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: default
  labels:
    app: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: gateway-secrets
              key: jwt-secret
        - name: USER_SERVICE_URL
          value: "http://user-service.default.svc.cluster.local:8081"
        - name: EXPERIMENT_SERVICE_URL
          value: "http://experiment-service.default.svc.cluster.local:8082"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service.default.svc.cluster.local:8083"
        - name: SUBMISSION_SERVICE_URL
          value: "http://submission-service.default.svc.cluster.local:8084"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5