# mysql-experiment-statefulset.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-experiment-headless
  labels:
    app: mysql-experiment
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mysql-experiment
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-experiment
  labels:
    app: mysql-experiment
spec:
  serviceName: mysql-experiment-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql-experiment
  template:
    metadata:
      labels:
        app: mysql-experiment
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: experiment-db-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: experiment-db-secret
              key: database
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
# 修改Service名称与Secret中的host保持一致
apiVersion: v1
kind: Service
metadata:
  name: mysql-experiment-service  # 修改为与Secret中host相同的名称
spec:
  selector:
    app: mysql-experiment
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP