# k8s/experiment-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: experiment-service
  namespace: default
spec:
  selector:
    app: experiment-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP