# k8s/submission-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: submission-service
  namespace: default
spec:
  selector:
    app: submission-service
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084
  type: ClusterIP