# k8s/notification-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: default
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP